# Generated by Django 3.0.2 on 2020-01-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('t', 'Transgender')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
