# Generated by Django 3.0.2 on 2020-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='bg_color',
            field=models.CharField(choices=[('#17A2B8', 'Magenta'), ('#DC3545', 'Red'), ('#28A745', 'Green'), ('#343A40', 'Dark Gray'), ('#007BFF', 'Blue'), ('#6C757D', 'Gray')], default='#343A40', max_length=7),
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
