# Generated by Django 3.0.2 on 2020-01-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_auto_20200111_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
