# Generated by Django 3.0.3 on 2020-02-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_note_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=50)),
                ('font_url', models.URLField()),
                ('font_alt', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='font',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='notesapp.Font'),
        ),
        migrations.AlterField(
            model_name='note',
            name='bg_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notesapp.Color'),
        ),
    ]
