# Generated by Django 3.0.3 on 2020-02-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_auto_20200215_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
